// Deterministic Connectivity IR -> KiCad renderer.
// Connectivity IR is the source of truth; the model never writes KiCad directly.
import { randomUUID } from 'node:crypto';

const GRID=2.54;
const esc=(v)=>String(v??'').replace(/\\/g,'\\\\').replace(/"/g,'\\"').replace(/[\r\n]+/g,' ');
const safe=(v)=>String(v||'item').replace(/[^A-Za-z0-9_+.-]/g,'_').slice(0,80)||'item';
const snap=(n)=>Math.round(Number(n)/GRID)*GRID;
const num=(n)=>Number(Number(n).toFixed(2)).toString();
const effects=(hide=false)=>`(effects (font (size 1.27 1.27))${hide?' hide':''})`;
const TYPES=new Set(['input','output','bidirectional','power_in','power_out','passive','tri_state','open_collector','no_connect','unspecified']);
const ANGLE={left:0,right:180,top:270,bottom:90},LDIR={left:'R',right:'L',top:'D',bottom:'U'},LTYPE={input:'I',output:'O',bidirectional:'B',power_in:'W',power_out:'w',passive:'P',tri_state:'T',open_collector:'C',no_connect:'N',unspecified:'U'};
function pagePoint(p={}){return{x:snap(25+Math.max(0,Math.min(1,Number(p.x??.5)))*160),y:snap(25+Math.max(0,Math.min(1,Number(p.y??.5)))*235)}};
function pinLayout(pins=[]){const sides={left:[],right:[],top:[],bottom:[]};for(const p of pins)(sides[p.side]||sides.left).push(p);const rows=Math.max(sides.left.length,sides.right.length,2),longest=Math.max(4,...pins.map(p=>String(p.name||'').length)),halfW=Math.max(5.08,snap((longest*.7+3)*1.27)),halfH=Math.max(5.08,snap((rows+1)*1.27)),pinLen=2.54,items=[],row=a=>a.map((_,i)=>snap((i-(a.length-1)/2)*GRID)),col=a=>a.map((_,i)=>snap((i-(a.length-1)/2)*GRID));row(sides.left).forEach((y,i)=>items.push({pin:sides.left[i],x:-(halfW+pinLen),y,side:'left'}));row(sides.right).forEach((y,i)=>items.push({pin:sides.right[i],x:halfW+pinLen,y,side:'right'}));col(sides.top).forEach((x,i)=>items.push({pin:sides.top[i],x,y:-(halfH+pinLen),side:'top'}));col(sides.bottom).forEach((x,i)=>items.push({pin:sides.bottom[i],x,y:halfH+pinLen,side:'bottom'}));return{halfW,halfH,pinLen,items};}
function librarySymbol(libId,pins){const g=pinLayout(pins),base=safe(libId.replace(':','_')),prefix=/^[RCLDFQJSTP]/i.test(base)?base[0].toUpperCase():'U',o=[`    (symbol "${esc(libId)}" (pin_names (offset 0.508)) (in_bom yes) (on_board yes)`,`      (property "Reference" "${prefix}" (at 0 ${num(-g.halfH-2.54)} 0) ${effects()})`,`      (property "Value" "${esc(libId.split(':').pop()||base)}" (at 0 ${num(g.halfH+2.54)} 0) ${effects()})`,`      (property "Footprint" "" (at 0 0 0) ${effects(true)})`,`      (property "Datasheet" "" (at 0 0 0) ${effects(true)})`,`      (symbol "${base}_0_1"`,`        (rectangle (start ${num(-g.halfW)} ${num(-g.halfH)}) (end ${num(g.halfW)} ${num(g.halfH)})`,`          (stroke (width 0.254) (type default)) (fill (type background)))`,`      )`,`      (symbol "${base}_1_1"`];for(const it of g.items){const p=it.pin,type=TYPES.has(p.type)?p.type:'unspecified';o.push(`        (pin ${type} line (at ${num(it.x)} ${num(it.y)} ${ANGLE[it.side]}) (length ${num(g.pinLen)})`);o.push(`          (name "${esc(p.name||p.number)}" ${effects()})`);o.push(`          (number "${esc(p.number)}" ${effects()}))`);}o.push('      )','    )');return{text:o.join('\n'),geometry:g};}
function compile(ir){const defs=new Map(),info=new Map();for(const c of ir.components){const wanted=c.libraryId||`Connectivity:${c.ref}`,sig=JSON.stringify(c.pins.map(p=>[p.number,p.name,p.type,p.side]));let libId=wanted;if(defs.has(libId)&&defs.get(libId).signature!==sig)libId=`Connectivity:${c.ref}`;if(!defs.has(libId))defs.set(libId,{...librarySymbol(libId,c.pins),signature:sig});info.set(c.ref,{libId,geometry:defs.get(libId).geometry,at:pagePoint(c.position)});}return{defs,info};}
function pinAt(comp,pin,info){const x=info.get(comp.ref);if(!x)return null;const item=x.geometry.items.find(i=>String(i.pin.number)===String(pin));if(!item)return null;return{x:snap(x.at.x+item.x),y:snap(x.at.y+item.y)};}
export function generateModernSchematic(ir){const root=randomUUID(),project='connectivity_reconstructed',{defs,info}=compile(ir),o=[`(kicad_sch (version 20250114) (generator "connectivity-intelligence-engine")`,`  (generator_version "1.0")`,`  (uuid ${root})`,`  (paper "A4")`,`  (lib_symbols`];for(const d of defs.values())o.push(d.text);o.push('  )');for(const c of ir.components){const x=info.get(c.ref);o.push('  (symbol');o.push(`    (lib_id "${esc(x.libId)}")`);o.push(`    (at ${num(x.at.x)} ${num(x.at.y)} 0)`);o.push('    (unit 1)','    (exclude_from_sim no)','    (in_bom yes)','    (on_board yes)','    (dnp no)');o.push(`    (uuid ${randomUUID()})`);o.push(`    (property "Reference" "${esc(c.ref)}" (at ${num(x.at.x)} ${num(x.at.y-5.08)} 0) ${effects()})`);o.push(`    (property "Value" "${esc(c.value||c.mpn||c.ref)}" (at ${num(x.at.x)} ${num(x.at.y+5.08)} 0) ${effects()})`);o.push(`    (property "Footprint" "${esc(c.footprint||'')}" (at ${num(x.at.x)} ${num(x.at.y)} 0) ${effects(true)})`);o.push(`    (property "Datasheet" "" (at ${num(x.at.x)} ${num(x.at.y)} 0) ${effects(true)})`);for(const p of c.pins)o.push(`    (pin "${esc(p.number)}" (uuid ${randomUUID()}))`);o.push('    (instances',`      (project "${project}"`,`        (path "/${root}"`,`          (reference "${esc(c.ref)}")`,'          (unit 1)','        )','      )','    )','  )');}
 // Labels at pin anchors preserve the Connectivity IR without asking AI to invent graphical routes.
 for(const net of ir.nets)for(const ep of net.endpoints){const c=ir.components.find(x=>x.ref===ep.ref),p=c?pinAt(c,ep.pin,info):null;if(p)o.push(`  (label "${esc(net.name)}" (at ${num(p.x)} ${num(p.y)} 0) ${effects()} (uuid ${randomUUID()}))`);}for(const nc of ir.noConnects||[]){const c=ir.components.find(x=>x.ref===nc.ref),p=c?pinAt(c,nc.pin,info):null;if(p)o.push(`  (no_connect (at ${num(p.x)} ${num(p.y)}) (uuid ${randomUUID()}))`);}o.push('  (sheet_instances','    (path "/" (page "1"))','  )','  (embedded_fonts no)',')');return{content:o.join('\n'),compInfo:info};}
function legacyName(id){return safe(id.replace(':','_'));}
function legacyDef(libId,pins){const g=pinLayout(pins),k=39.37007874,o=['#',`# ${legacyName(libId)}`,'#',`DEF ${legacyName(libId)} U 0 40 Y Y 1 F N`,'DRAW',`S ${Math.round(-g.halfW*k)} ${Math.round(-g.halfH*k)} ${Math.round(g.halfW*k)} ${Math.round(g.halfH*k)} 0 1 10 f`];for(const it of g.items){const p=it.pin;o.push(`X ${safe(p.name||p.number)} ${safe(p.number)} ${Math.round(it.x*k)} ${Math.round(-it.y*k)} ${Math.round(g.pinLen*k)} ${LDIR[it.side]} 50 50 1 1 ${LTYPE[p.type]||'U'}`);}o.push('ENDDRAW','ENDDEF');return o.join('\n');}
export function generateLegacySchematic(ir){const k=39.37007874,{defs,info}=compile(ir),cache=['EESchema-LIBRARY Version 2.4','#encoding utf-8'];for(const [id,d] of defs.entries())cache.push(legacyDef(id,d.geometry.items.map(x=>x.pin)));cache.push('#End Library');const o=['EESchema Schematic File Version 4','LIBS:reconstructed-cache','EELAYER 29 0','EELAYER END','$Descr A4 11693 8268','Sheet 1 1',`Title "${esc(ir.title)}"`,'$EndDescr'];for(const c of ir.components){const x=info.get(c.ref),px=Math.round(x.at.x*k),py=Math.round(x.at.y*k);o.push('$Comp',`L ${legacyName(x.libId)} ${safe(c.ref)}`,`U 1 1 ${randomUUID().replace(/-/g,'').slice(0,8).toUpperCase()}`,`P ${px} ${py}`,`F 0 "${esc(c.ref)}" H ${px} ${py-150} 50  0000 C CNN`,`F 1 "${esc(c.value||c.mpn||c.ref)}" H ${px} ${py+150} 50  0000 C CNN`,`F 2 "${esc(c.footprint||'')}" H ${px} ${py} 50  0001 C CNN`,`\t1    ${px} ${py}`,'\t1    0    0    -1','$EndComp');}for(const net of ir.nets)for(const ep of net.endpoints){const c=ir.components.find(x=>x.ref===ep.ref),p=c?pinAt(c,ep.pin,info):null;if(p)o.push(`Text Label ${Math.round(p.x*k)} ${Math.round(p.y*k)} 0    50   ~ 0`,esc(net.name));}o.push('$EndSCHEMATC');return{schematic:o.join('\n'),cacheLib:cache.join('\n')};}
const xml=(v)=>String(v??'').replace(/&/g,'&amp;').replace(/</g,'&lt;').replace(/>/g,'&gt;').replace(/"/g,'&quot;');
export function generateSchematicPreviewSvg(ir){const{info}=compile(ir),W=920,H=620,sx=x=>x/210*W,sy=y=>y/297*H,o=[`<svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 ${W} ${H}">`,'<rect width="100%" height="100%" fill="white"/>'];for(const net of ir.nets){const pts=net.endpoints.map(ep=>{const c=ir.components.find(x=>x.ref===ep.ref);return c?pinAt(c,ep.pin,info):null;}).filter(Boolean);if(pts.length>1){const a=pts[0];for(const b of pts.slice(1))o.push(`<path d="M ${sx(a.x)} ${sy(a.y)} L ${sx(b.x)} ${sy(b.y)}" stroke="#9aa4b2" stroke-width="1.5" fill="none"/>`);}}for(const c of ir.components){const x=info.get(c.ref),g=x.geometry;o.push(`<rect x="${sx(x.at.x-g.halfW)}" y="${sy(x.at.y-g.halfH)}" width="${sx(g.halfW*2)}" height="${sy(g.halfH*2)}" fill="#f8fafc" stroke="#334155" stroke-width="1.2" rx="3"/>`);o.push(`<text x="${sx(x.at.x)}" y="${sy(x.at.y)-3}" text-anchor="middle" font-family="sans-serif" font-size="11" font-weight="700">${xml(c.ref)}</text>`);o.push(`<text x="${sx(x.at.x)}" y="${sy(x.at.y)+11}" text-anchor="middle" font-family="sans-serif" font-size="9">${xml(c.value)}</text>`);}o.push('</svg>');return o.join('');}
export function buildSchematicFiles(ir){const modern=generateModernSchematic(ir),legacy=generateLegacySchematic(ir),report={schemaVersion:ir.schemaVersion,title:ir.title,confidence:ir.confidence,componentCount:ir.components.length,netCount:ir.nets.length,interfaceCount:ir.interfaces?.length||0,issueCount:ir.issues?.length||0,health:ir.health,warnings:ir.warnings,note:'Connectivity IR is the source of truth. KiCad schematic is a deterministic human-review renderer.'},irJson=JSON.stringify(ir,null,2);return{files:[{path:'reconstructed.kicad_sch',content:modern.content,contentType:'text/plain'},{path:'reconstructed.sch',content:legacy.schematic,contentType:'text/plain'},{path:'reconstructed-cache.lib',content:legacy.cacheLib,contentType:'text/plain'},{path:'connectivity-ir.json',content:irJson,contentType:'application/json'},{path:'schematic-ir.json',content:irJson,contentType:'application/json'},{path:'connectivity-report.json',content:JSON.stringify(report,null,2),contentType:'application/json'}],previewSvg:generateSchematicPreviewSvg(ir),report};}
